kyma-project/kyma-metrics-collector

.gitignore, CODEOWNERS
- chore: updated codeowners and gitignore
- https://github.com/kyma-project/control-plane/issues/3327
=> chore: updated codeowners and gitignore

sec-scanners-config.yaml
- added sec-scanners-config.yaml
- https://github.com/kyma-project/control-plane/issues/3327
=> chore: added sec-scanners-config.yaml

.github/workflows/lint-conventional-prs.yml
- added PR title lint job
- https://github.com/kyma-project/control-plane/issues/3327
=> chore: added PR title lint job

Makefile, README.md, metrics.md, pkg/process/metrics.go
- Updated documentation
- https://github.com/kyma-project/control-plane/issues/3327
=> chore: updated documentation

.github/dependabot.yml
- enable dependabot with default settings
=> chore: enable-dependabot

.github/release.yml, .github/workflows/create-release.yml, .gitignore, hack/scripts/await_pr_merge.sh, hack/scripts/check_artifacts_existence.sh, hack/scripts/create_scan_config.sh, hack/scripts/create_sec_scanner_bump_pr.sh, hack/scripts/releaselabelvalidator/release_label_validator.py, hack/scripts/releaselabelvalidator/requirements.txt
- Added the following jobs:
- validate-release
- Bump sec-scanners-config
- run-unit-tests
=> chore: implement automated release workflow - part 1

.gitignore, resources/kyma-metrics-collector/.helmignore, resources/kyma-metrics-collector/Chart.yaml, resources/kyma-metrics-collector/templates/_helpers.tpl, resources/kyma-metrics-collector/templates/deployment.yaml, resources/kyma-metrics-collector/templates/policy.yaml, resources/kyma-metrics-collector/templates/prometheusrule.yaml, resources/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml, resources/kyma-metrics-collector/templates/role.yaml, resources/kyma-metrics-collector/templates/rolebinding.yaml, resources/kyma-metrics-collector/templates/secrets.yaml, resources/kyma-metrics-collector/templates/service-account.yaml, resources/kyma-metrics-collector/templates/service-monitor.yaml, resources/kyma-metrics-collector/templates/service.yaml, resources/kyma-metrics-collector/templates/vm-service-scrape.yaml, resources/kyma-metrics-collector/values.yaml
- moved helm chart from control-plane to KMC repo
=> chore: moved helm chart from control-plane to KMC repo

.github/workflows/create-release.yml, hack/scripts/check_artifacts_existence.sh
- fixed commit ref for release pipeline
=> fix: fixed commit ref for release pipeline

.github/workflows/create-release.yml
- fixed needs for publish-release step in create release workflow
=> fixed: fixed needs for publish-release step in create release workflow

.github/workflows/create-release.yml
- enabled validate labels step in create release workflow
=> chore: enabled validate labels step in create release workflow

Dockerfile, go.mod
=> chore: update go patch version

hack/schema/dev-stage/schema.json, hack/schema/prod/schema.json
- add current version of the edp schemata
=> chore: add current schemata

.github/dependabot.yml, CODEOWNERS
- **update codeowners**
- **fix codeowners**
- **group dependabot bumps by api groups**
=> chore: group dependabot

README.md
- Added mandatory sections to README.md
https://github.com/kyma-project/community/issues/926
=> docs: add mandatory sections to readme

.gitignore, LICENSES/Apache-2.0.txt
- added missing licenses folder for reuse compliance
- ...
- ...
=> chore: added missing licenses folder

.github/workflows/pr-github-checks.yml
- add github checks similar to telemetry-manager repo
- ...
- ...
=> chore: add github checks

.github/workflows/create-release.yml, .github/workflows/pr-all-checks-passed.yml, sec-scanners-config.yaml
=> chore: Use build image directly

.github/workflows/create-release.yml, sec-scanners-config.yaml
=> chore: Fix typo in gha definition

.github/workflows/pr-docu-checks.yml, .github/workflows/pr-github-checks.yml
=> chore: Exclude checks during merge_group

.github/dependabot.yml
- Group Otel dependencies in dependabot PRs
-
=> chore: Group otel dependencies

.github/workflows/create-release.yml
- fix the publish release workflow step
-
=> chore: Fix publish release step

Dockerfile, go.mod, internal/tools/go.mod
=> chore: Update to golang 1.23.5

sec-scanners-config.yaml
=> chore: Fix checkmarx config

.github/workflows/pr-github-checks.yml
- from here on forward we will allow all lower case titles (to allow Renovate PRs to be merged)
-
=> chore: Change title validation to lower case

.github/workflows/pr-github-checks.yml, .github/workflows/titleprefix_to_label.json, renovate.json
- enable automatic labelling and milestoning
- sync renovate config with telemetry-manager
-
=> chore: enable label and milestone automation

renovate.json
=> chore: enable gha update, disable dependabot

cmd/main.go, pkg/process/process.go, pkg/runtime/clients.go
- **assign missing client factory**
- **process constructor**
- **reformat files**
- fixed crash introduced here: #158
=> fix: missing clientfactory crashes kmc on startup

go.mod, go.sum
=> chore: Bump x/oauth2 dependency

.github/workflows/build-image.yml, .github/workflows/pr-all-checks-passed.yml, .github/workflows/pr-github-checks.yml, renovate.json
- chore: update gh action to proper release versions
-
=> chore: update gh action to proper release versions

.github/workflows/create-release.yml
- add missing privileges to build image and create release
-
=> chore: add missing privileges
